[Sign Up] User have an error on sign up when enter 1 letter name
ita-social-projects/GreenCityUser pull request #210
Opened 2023-02-07 19:14 UTC by ABbondar

# GreenCityUser PR
https://github.com/ita-social-projects/GreenCity/issues/5206

## Summary Of Changes :fire:
Modified regexp pattern on OwnSignUpDto "name" field

## Issue Link :clipboard:
_&lt;Link to the issue&gt;_

## Added
Added tests for regexp patterns

## Changed
* _&lt;detail item of what was changed&gt;_
* _&lt;describe functionality that was changed&gt;_

## Deleted
* _&lt;detail item of what was removed&gt;_

## How to test :clipboard:
Running tests in OwnSignUpDtoTest class

# PR Checklist Forms

_(to be filled out by PR submitter)_
- [ ] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-XXXX: Ticket title)
- [x] This template filled (above this section).
- [x] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells ar duplication
- [ ] `NEED_REVIEW` and `READY_FOR_REVIEW` labels are added.
- [x] All files reviewed before sending to reviewers

2023-02-07 19:28 UTC, LiliaMokhnatska approved these changes

2023-02-07 19:28 UTC, Markiro1 approved these changes

2023-02-07 19:35 UTC, juseti approved these changes

2023-02-08 11:04 UTC, RomaMocherniuk commented on service-api/src/main/java/greencity/security/dto/ownsecurity/OwnSignUpDto.java
>          message = ValidationConstants.INVALID_USERNAME)
What is the value of `ValidationConstants.INVALID_USERNAME`
Should we also update it too?

2023-02-08 12:06 UTC, ABbondar commented on service-api/src/main/java/greencity/security/dto/ownsecurity/OwnSignUpDto.java
>          message = ValidationConstants.INVALID_USERNAME)
updated

2023-02-14 15:29 UTC, RomaMocherniuk commented on service-api/src/main/java/greencity/security/dto/ownsecurity/OwnSignUpDto.java
> -        max = ValidationConstants.USERNAME_MAX_LENGTH)
I see that ` UserForListDto, UserManagementDto, UserManagementUpdateDto, UserUpdateDto, EmployeeSignUpDto` use the same validation  
   ```
    min = ValidationConstants.USERNAME_MIN_LENGTH,
    max = ValidationConstants.USERNAME_MAX_LENGTH)
```
Should it also be changed to `regexp = ValidationConstants.USERNAME_REGEXP`?

2023-02-14 15:29 UTC, RomaMocherniuk requested changes
Left a comment

2023-03-01 09:15 UTC, RomaMocherniuk approved these changes

2023-03-01 09:19 UTC, merged