add email preference feature
ita-social-projects/GreenCityUser pull request #383
Opened 2024-08-28 09:45 UTC by holotsvan

2024-08-28 17:09 UTC, Maryna-511750 approved these changes

2024-08-29 06:22 UTC, IliaWithHat approved these changes

2024-08-29 07:59 UTC, KizerovDmitriy requested changes

2024-08-29 07:59 UTC, KizerovDmitriy commented on service/src/main/java/greencity/service/UserServiceImpl.java
> +import greencity.entity.*;
we don't use wildcard imports

2024-08-29 07:59 UTC, KizerovDmitriy commented on service/src/main/java/greencity/service/UserServiceImpl.java
> +import java.util.*;
same

2024-08-29 07:59 UTC, KizerovDmitriy commented on service/src/test/java/greencity/service/UserServiceImplTest.java
> +import greencity.repository.*;
and here

2024-08-30 08:59 UTC, holotsvan commented on service/src/test/java/greencity/service/UserServiceImplTest.java
> +import greencity.repository.*;
remove wildcards

2024-08-30 11:08 UTC, KizerovDmitriy approved these changes

2024-09-10 06:24 UTC, merged