Fix core, service and service-api issues
ita-social-projects/GreenCityUser pull request #403
Opened 2024-09-30 15:07 UTC by K4sik

# GreenCityUser PR
Fix Sonar Issues in GreenCityUser service and service-API modules

## Issue Link :clipboard:
#[7532](https://github.com/orgs/ita-social-projects/projects/43/views/1?pane=issue&itemId=81573167) 

## Summary Of Changes :fire:

## Changed
* ApiLocate.java by removing section @Parameters;
* CustomExceptionHandlerTest.java by removing unnecessary commented test cases and fixed assignment of values;
* ManagementSecurityControllerTest.java by removing useless assignments to local variable "dto";
* JwtTool.java - throw a dedicated exception IllegalArgumentException instead of using RuntimeException;
* Adde annotation @SuppressWarnings("java:S1118") to EmailAddressValidator, LanguageValidationUtils, and UrlValidator for skipping Sonar Issue;
* Removed usage of "initMocks" because of its deprecation and added @ExtendWith(MockitoExtension.class) instead in SearchCriteriaTest.java, CustomSpecificationTest.java, and UserSpecificationTest.java.
* Renamed field "notVerifiedUser" and refactored the code of the lambdas to have only one invocation possibly throwing an exception in OwnSecurityServiceImplTest.java;
* Removed block of commented-out lines of code which should be deleted VerifyEmailServiceImplTest.java;
* Renamed obj "user" which has already been declared, removed useless assignment to local variable "sixFriendsWithOnlineStatusDtos" and "friendsWithOnlineStatusDtos" in UserServiceImplTest.java.

# PR Checklist Forms

_(to be filled out by PR submitter)_
- [ ] Code is up-to-date with the dev branch.
- [X] You've successfully built and run the tests locally.
- [X] New or updated unit tests validate the change.
- [X] JIRA/ Github Issue number & title in PR title (ISSUE-#[7532](https://github.com/orgs/ita-social-projects/projects/43/views/1?pane=issue&itemId=81573167))
- [X] This template is filled (above this section).
- [X] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells or duplication
- [X] NEED_REVIEW and READY_FOR_REVIEW labels are added.
- [X] All files reviewed before sending to reviewers

2024-09-30 15:26 UTC, holotsvan approved these changes

2024-09-30 16:01 UTC, Maryna-511750 approved these changes

2024-10-01 09:35 UTC, KizerovDmitriy requested changes

2024-10-01 09:35 UTC, KizerovDmitriy commented on service-api/src/main/java/greencity/security/jwt/JwtTool.java
> +            throw new IllegalArgumentException("Error parsing JSON payload", e);
did we having handler for current exception?

2024-10-01 09:56 UTC, K4sik commented on service-api/src/main/java/greencity/security/jwt/JwtTool.java
> +            throw new IllegalArgumentException("Error parsing JSON payload", e);
Yes, now we have exception handler for IllegalArgumentException.

2024-10-01 10:03 UTC, KizerovDmitriy approved these changes

2024-10-01 10:20 UTC, merged